import argparse
import sys

from toybands.plottools import plot_from_csv

def plotcsv():
    my_parser = argparse.ArgumentParser(
        prog="plotcsv", description="Plot csv file previously generated by toybands"
    )
    my_parser.add_argument(
    "-f",
    metavar="path_for_file",
    type=str,
    help="path of csv file to plot"
    )
    args = my_parser.parse_args()
    plot_from_csv(args.f)

if __name__ == "__main__":
    plotcsv()